# Site settings
title: Enenamah David - Software Engineer
email: denenama@gmail.com
description: >- # this means to ignore newlines until next property
  Software Engineer with 3 years of experience in developing robust, scalable web applications. 
  Passionate about creating innovative solutions and continuous learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://franzego.github.io" # the base hostname & protocol for your site
github_username: franzego
linkedin_username: davidenenamah@gmail.com

# Build settings
theme: jekyll-theme-minimal # You can change this to other GitHub Pages supported themes
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

