# Site basic settings
title: Enenamah David - Software Engineer
email: denenama@example.com
description: Linux infrastructure specialist | Virtualization Expert | Cloud Solutions

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Basic profile
author:
  name: Enenamah David
  bio: Software Engineer specializing in Linux and cloud infrastructure

# Social links
github_username: franzego
linkedin_username: franzego

# Minimal configuration details
contact:
  email: your.email@example.com
  location: City, Country

# Exclude standard files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
